### PR TITLE
Window weld unit test

### PR DESCRIPTION
**Pull request by boblannon**
This adds unit tests for the `match_combinations_as_windows` and `match_combinations_as_prefixes` functions.

### CODE REVIEW

**Comment by boblannon** [comment]
hm, weird that coverage didn't increase there...

**Comment by apendleton** [comment]
These code paths were likely already tested indirectly via the glue tests, such as they were?

**Comment by boblannon** [comment]
right, yeah, was just double-checking that.  definitely true.  are they still worth having, though?

**Comment by apendleton** [comment]
That's a fair question... I'll admit that partly I was thinking we would unit-test each component separately out of principle rather than because I'm necessarily super-convinced that it's necessary to be confident that the whole library works as specified, as a unit. That said, to the extent that unit tests are meant to catch regressions going forward, I think there's value in having tests whose scope are reasonably constrained. The glue tests cover enough disparate, complicated components with complex interactions that if we *were* to introduce a regression, I think it could be challenging to figure out where it originated.

**Comment by boblannon** [comment]
yeah, +1. I certainly feel better about having direct unit tests in addition to the glue tests.

**Comment by apendleton** [comment]
Anyhow, similar to my conversation with @aarthykc this morning, I think assuming we do want to have tests here, it might be useful to cover some cases that are likely to come up in the context of real-world applications where we're searching over a whole query, not all of which is a match in this particular index. The extent to which we can do that here vs. in the glue code is somewhat constrained, since words not included in our index are outside our purview (those kinds of queries are not expressible in a way that can be sent to the phrase graph code since everything needs to be expressed in terms of word IDs). Still: some tests where matches ought to fail, or where there are extra words that we do know about that don't form part of a match (e.g., "100 main st washington" where maybe we do know about "washington" as a word because there's a "washington st" even though in this context it's not part of a street name), or where there are two matches back to back or two matches, one of which is a strict prefix of the other, etc.

To make that possible, we may need to augment our test data, possibly with an additional file, with some specifically construct index entries designed to trigger some of these behaviors (and bonus: it should cover a couple of still-uncovered lines in the coverage report).

**Comment by boblannon** [comment]
so per that discussion in #43, would this be in a separate `phrase/fuzz_tests.rs`?

**Comment by apendleton** [comment]
@boblannon I don't think so? I separated out `fuzz_tests.rs` for glue because it requires downloading a giant file and takes a long time to build. What I'm proposing here is to add a single-digit number of additional phrases to make sure we have, e.g., some examples of phrases that overlap with one another, so that we can write specific, targeted unit tests against them.

Like: adding both "100 main" and "100 main st" to make sure we catch both on a single windowed traversal of "100 main st". None of the current set of tests ever return more than one result, if I'm not mistaken, so we should be confident that that actually works.

But however you want to do it is fine. I admittedly muddied the waters on the phrase side because I had the side motivation of wanting to be able to write tests that did lookups on strings for legibility reasons.

**Comment by apendleton** [comment]
Took this one over from Bob, and added a bunch of corner-case tests per my last comment, plus caught a case with not-great error handling in windowed-search and fixed it.

**Pull request merged**
