### PR TITLE
[phrase] benchmarks

### PR DESCRIPTION
**Pull request by boblannon**
This PR adds benchmark code for 

- `PhraseSet::contains`
- `PhraseSet::contains_prefix`
  - vanilla case, where query is entirely made up of `QueryWord::Full`
  - autocomplete case, where last word in query is `QueryWord::Prefix`. This case calls `PhraseSet::contains_prefix_range` indirectly

### CODE REVIEW

**Comment by boblannon** [comment]
right now, the `range_contains_prefix` bench is not great.  because the word_ids are auto-incremented, there are no gaps in the phrase graph, so the more complex logic (see [here](https://github.com/mapbox/fuzzy-phrase/blob/ae9c7df62dfe97efbc37584740df48e42a7ae6a2/src/phrase/mod.rs#L170-L294)]) never gets touched.

One way I think i can address this is by auto-incrementing by a random integer [here](https://github.com/mapbox/fuzzy-phrase/blob/ae9c7df62dfe97efbc37584740df48e42a7ae6a2/benches/phrase.rs#L25).  I wonder, though, if there are any tools available for determining whether benchmark code has good coverage.

**Comment by apendleton** [comment]
@boblannon yeah, I think to be more confident we'd want to more closely emulate real behavior, which is to say: IDs are assigned to words lexicographically rather than in whatever order they're seen (which is what I think is happening now?), so that ranges actually represent prefixes. Part of me wants to keep testing each component in isolation, but maybe doing that here will involve more wheel reinvention than is worthwhile and we should compromise and just use existing code from other components to make this easy. If we do continue to keep things separate, though, a simpler but less efficient mock of the real prefix code might go something like this:
* plan to do two passes through the phrase sample file
* on the first pass, segment by whitespace and add each word you see to a set (HashSet is fine, but BTreeSet has the nice advantage that they're sorted internally so if you iterate on the contents later you get them out in order)
* after that pass, iterate over your sorted word set and build a word -> lex ID hashmap
* rewind the buffer (`seek(0)` I think?) and do a second pass through the phrase file, and rather than using autoinc IDs, use the real IDs you assigned in the first pass
* do some prefix lookups that actually select a real prefix of actual words in your set, and ascertain their ranges just by doing a linear scan through your word set and identifying the first and last words that have the given prefix (can be like `btree_set.iter().enumerate().skip_while()` to skip up to the first one, then `.take_while()` to get to the last one)

You'd want to do the linear scans outside your bench iter -- so, decide what the ID ranges are going to be in advance -- since that part will be far enough from optimal that it might influence your results.

As for coverage: I'm looking at [tarpaulin](https://github.com/xd009642/tarpaulin) for test coverage, but was going to skip benches for now. We could look at including it on a subsequent pass, though.

**Comment by boblannon** [comment]
okay, re-did things to assign IDs lexicographically.  interestingly, I couldn't use the `seek()` method on the buffer, because it's borrowed in `for line of file_buf.lines()`.  I need to understand that better, but for now shadowing is my cop-out

**Comment by apendleton** [comment]
Yeah, shadowing seems fine. This looks good to me. Might be worth either figuring out if it's possible to run benches under tarpaulin (not obviously but maybe?) or reusing some code between benches and tests, so that one way or another you could get coverage reports to see if this code does indeed exercise all corners of the search exploration there. Doesn't feel like something to block this PR though.

**Comment by boblannon** [comment]
>figuring out if it's possible to run benches under tarpaulin (not obviously but maybe?)

yeah, not sure, but I'd be interested to know. one thing that might help is moving the individual benchmark functions into the crate proper. like `benches/prefix.rs` and `benches/phrase.rs` could both be moved to their respective modules, and then imported in `benches/benchmarks.rs`. if we did that, then we might be able to do bench coverage by marking those functions with `#[bench]` (which is still experimental/nightly).

**Comment by apendleton** [comment]
`#[bench]` specifically integrates with the built-in bench framework available in nightly, to which `criterion` is an alternative. The sense that I got looking at tickets when researching libraries is that it was an experiment to see if a one-size-fits-most solution makes sense for benching the way it has for tests, and the general consensus has been "no," or at least, that that isn't it, and that it will likely never be stabilized, in favor of instead letting the ecosystem figure it out. On that side, `criterion` seems to be the most popular entrant, but doesn't work with annotations like that.

So... I don't think so? Also I don't want to depend on nightly anyway unless we absolutely have to. And we can move some of the code in and then expose it to criterion, but it means making those internal mocking functions part of the public-facing API contract, which has semver implications and just generally seems weird. So the answer might turn out to be no, but that might not be the end of the world. Like we've talked about before, an integration test that uses real data to try to be completist about exploring code paths and a benchmark are actually kind of different functions, and while it would be good not to do too much code duplication, maybe a little isn't the end of the world. In the bench context, I feel like the top priority should be that the bench data is representative of real world data, and if real world data explores some code paths seldom or never, the benches probably shouldn't either -- the speed of code paths that only get exercised in exceptional cases isn't that important anyway as they'll never end up being bottlenecks.

**Comment by boblannon** [comment]
>  The sense that I got looking at tickets when researching libraries is that it was an experiment to see if a one-size-fits-most solution makes sense for benching the way it has for tests, and the general consensus has been "no," or at least, that that isn't it

Okay, yeah, I did some some threads that seemed to point in that direction (or anyway went cold without a resolution).

> And we can move some of the code in and then expose it to criterion, but it means making those internal mocking functions part of the public-facing API contract, which has semver implications and just generally seems weird. 

Hadn't considered that, but you're right.

Another reason not to do it might be if we're going make it possible to point at benchmark data via some kind of config file or env variable.

>  In the bench context, I feel like the top priority should be that the bench data is representative of real world data, and if real world data explores some code paths seldom or never, the benches probably shouldn't either 

Point taken. I'm mostly interested in getting some sense of worst-cases and how they impact performance. I can probably make myself feel better on that score by just running bench data through and having some debug output to assure me that branches of logic are being hit.

There's more to discuss but I'll merge this now and we can take it up in future work.

**Pull request merged**
